version: '3.4'
services:
  api:
    build:
      context: .
    container_name: spring-app
    # command: /bin/bash -c "java -jar app.jar"
    restart: always
    ports:
      - "8080:8080"
    image: spring-app:test
    # logging:
    #  driver: "awslogs"
    #  options:
    #     awslogs-region: "us-east-1"
    #     awslogs-group: "/aws/ec2/instance/ spring-app"
    #     tag: "${TAG}/{{.Name}}/{{.ID}}"